# Generated by Django 5.1.3 on 2025-11-14 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loginsystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('target_audience', models.CharField(choices=[('all', 'All Users'), ('students', 'Students Only'), ('companies', 'Companies Only'), ('admins', 'Admins Only')], default='all', max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('read', 'Read'), ('replied', 'Replied'), ('closed', 'Closed')], default='new', max_length=20)),
                ('received_date', models.DateTimeField(auto_now_add=True)),
                ('admin_notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlacementReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_title', models.CharField(max_length=200)),
                ('generated_date', models.DateTimeField(auto_now_add=True)),
                ('report_type', models.CharField(choices=[('monthly', 'Monthly Report'), ('yearly', 'Yearly Report'), ('placement', 'Placement Drive Report'), ('custom', 'Custom Report')], max_length=50)),
                ('data', models.JSONField(default=dict)),
                ('generated_by', models.CharField(max_length=100)),
                ('file_path', models.FileField(blank=True, null=True, upload_to='reports/')),
            ],
        ),
        migrations.CreateModel(
            name='SystemAnalytic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(max_length=100)),
                ('metric_value', models.JSONField(default=dict)),
                ('recorded_date', models.DateField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlacementDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drive_name', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('companies', models.ManyToManyField(blank=True, to='loginsystem.company')),
                ('participating_students', models.ManyToManyField(blank=True, to='loginsystem.student')),
            ],
        ),
    ]
